// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Altstore",
    columns: [
      { name: "Userid", type: "string" },
      { name: "Foldername", type: "string" },
      { name: "User_mail", type: "string" },
    ],
  },
  { name: "Filedata", columns: [] },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Altstore = InferredTypes["Altstore"];
export type AltstoreRecord = Altstore & XataRecord;

export type Filedata = InferredTypes["Filedata"];
export type FiledataRecord = Filedata & XataRecord;

export type DatabaseSchema = {
  Altstore: AltstoreRecord;
  Filedata: FiledataRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Poorna-Prakash-s-workspace-g2an37.us-east-1.xata.sh/db/Storage",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
